// All inline style objects for the game UI
export const S = {
  app: { width: "100%", height: "100vh", display: "flex", flexDirection: "column", fontFamily: "'Segoe UI', -apple-system, sans-serif", overflow: "hidden", color: "#e2e8f0" },
  topHud: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 16px", background: "#0a0f1aee", borderBottom: "1px solid #1a2a4a", zIndex: 20, flexWrap: "wrap", gap: "8px" },
  hudLeft: { display: "flex", alignItems: "center", gap: "12px" },
  cityLabel: { fontSize: "15px", fontWeight: 800, color: "#fff" },
  climateLabel: { fontSize: "10px", color: "#64748b", fontWeight: 600 },
  hudStats: { display: "flex", gap: "6px", flexWrap: "wrap", alignItems: "center" },
  resourceBox: { display: "flex", alignItems: "center", gap: "6px", padding: "4px 10px", borderRadius: "8px", background: "#ffffff08", border: "1px solid #ffffff10" },
  resourceIcon: { display: "flex", alignItems: "center", justifyContent: "center", width: "24px", height: "24px", borderRadius: "6px", background: "#ffffff0a", flexShrink: 0 },
  resourceInfo: { display: "flex", flexDirection: "column", gap: "0px", minWidth: 0 },
  resourceLabel: { fontSize: "8px", fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.5px", lineHeight: 1 },
  resourceVal: { fontSize: "13px", fontWeight: 800, fontFamily: "monospace", lineHeight: 1.2 },
  satisfactionBar: { width: "48px", height: "4px", background: "#1a2a40", borderRadius: "2px", overflow: "hidden" },
  satisfactionFill: { height: "100%", borderRadius: "2px", transition: "width 0.5s, background 0.5s" },
  hudStat: { display: "flex", alignItems: "center", gap: "4px", fontSize: "12px" },
  hudStatVal: { fontWeight: 700, fontFamily: "monospace", fontSize: "13px", color: "#e2e8f0" },
  hudRight: { display: "flex", alignItems: "center", gap: "8px" },
  speedControls: { display: "flex", gap: "2px" },
  speedBtn: { padding: "2px 8px", borderRadius: "4px", border: "1px solid #2a3a5e", cursor: "pointer", fontSize: "8px", fontFamily: "inherit" },
  mainArea: { display: "flex", flex: 1, overflow: "hidden" },
  toolbar: { width: "56px", background: "#0a0f1aee", borderRight: "1px solid #1a2a4a", display: "flex", flexDirection: "column", padding: "6px 4px", gap: "2px", zIndex: 10 },
  toolBtn: { display: "flex", flexDirection: "column", alignItems: "center", gap: "1px", padding: "6px 4px", borderRadius: "6px", border: "2px solid", cursor: "pointer", background: "none", transition: "all 0.15s" },
  toolLabel: { fontSize: "7px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.3px" },
  viewport: { flex: 1, overflow: "hidden", position: "relative", cursor: "grab" },
  rightPanel: { width: "200px", background: "#0a0f1aee", borderLeft: "1px solid #1a2a4a", overflowY: "auto", display: "flex", flexDirection: "column", gap: "0", zIndex: 10 },
  subPanel: { padding: "10px", borderBottom: "1px solid #1a2a4a" },
  subTitle: { fontSize: "12px", fontWeight: 800, color: "#f59e0b", marginBottom: "8px" },
  sectionLabel: { fontSize: "9px", fontWeight: 700, color: "#64748b", textTransform: "uppercase", letterSpacing: "1px", margin: "6px 0 4px", padding: "0 2px" },
  buildGrid: { display: "flex", flexDirection: "column", gap: "3px" },
  buildItem: { display: "flex", alignItems: "center", gap: "8px", padding: "6px 8px", borderRadius: "6px", border: "1px solid", cursor: "pointer", background: "none", textAlign: "left", transition: "all 0.15s" },
  buildName: { fontSize: "11px", fontWeight: 600, color: "#e2e8f0", flex: 1 },
  buildCost: { fontSize: "9px", color: "#fbbf24", fontWeight: 700, fontFamily: "monospace" },
  zoneBtn: { display: "flex", alignItems: "center", gap: "8px", padding: "8px 10px", borderRadius: "6px", border: "2px solid", cursor: "pointer", background: "none", width: "100%", marginBottom: "4px", transition: "all 0.15s" },
  zoneName: { fontSize: "12px", fontWeight: 600, color: "#e2e8f0" },
  zoneHint: { fontSize: "9px", color: "#64748b", marginTop: "6px" },
  roadInfo: { display: "flex", flexDirection: "column", gap: "6px" },
  roadCost: { fontSize: "13px", fontWeight: 700, color: "#fbbf24" },
  roadHint: { fontSize: "10px", color: "#94a3b8", lineHeight: 1.4 },
  infoGrid: { display: "flex", flexDirection: "column", gap: "4px" },
  infoRow: { display: "flex", justifyContent: "space-between", fontSize: "11px" },
  infoLabel: { color: "#64748b", fontWeight: 600 },
  infoVal: { color: "#e2e8f0", fontWeight: 700, fontFamily: "monospace" },
  minimapWrap: { padding: "10px", borderTop: "1px solid #1a2a4a", marginTop: "auto" },
  minimapTitle: { fontSize: "9px", fontWeight: 700, color: "#64748b", marginBottom: "4px", textTransform: "uppercase", letterSpacing: "1px" },
  minimap: { border: "1px solid #2a3a5e", borderRadius: "4px", overflow: "hidden", lineHeight: 0 },
  notifArea: { position: "fixed", bottom: "40px", left: "72px", zIndex: 30, display: "flex", flexDirection: "column", gap: "4px" },
  notif: { padding: "6px 14px", borderRadius: "6px", background: "#0a0f1aee", border: "1px solid #2a3a5e", color: "#fbbf24", fontSize: "11px", fontWeight: 600, animation: "fadeIn 0.2s" },
  bottomDock: { background: "#0a0f1aee", borderTop: "1px solid #1a2a4a", zIndex: 20, position: "relative" },
  dockInner: { display: "flex", justifyContent: "center", gap: "4px", padding: "6px 16px" },
  dockBtn: { display: "flex", flexDirection: "column", alignItems: "center", gap: "3px", padding: "6px 14px", borderRadius: "10px", border: "2px solid", cursor: "pointer", background: "none", transition: "all 0.2s", minWidth: "64px" },
  dockIcon: { width: "44px", height: "44px", borderRadius: "10px", border: "1px solid", display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s" },
  dockLabel: { fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.5px", transition: "color 0.2s" },
  dockPanel: { position: "absolute", bottom: "100%", left: "50%", transform: "translateX(-50%)", width: "400px", maxWidth: "90vw", background: "#0d1520", border: "1px solid #1a2a4a", borderRadius: "12px 12px 0 0", boxShadow: "0 -8px 32px rgba(0,0,0,0.4)", overflow: "hidden" },
  dockPanelHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 16px", borderBottom: "1px solid #1a2a4a" },
  dockPanelTitle: { fontSize: "13px", fontWeight: 800, color: "#f59e0b" },
  dockPanelClose: { background: "none", border: "none", color: "#64748b", fontSize: "18px", cursor: "pointer", padding: "0 4px" },
  dockPanelBody: { padding: "20px 16px", minHeight: "80px", display: "flex", alignItems: "center", justifyContent: "center" },
  dockPanelEmpty: { fontSize: "12px", color: "#475569", fontStyle: "italic" },
  statusBar: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "3px 16px", background: "#080c16", borderTop: "1px solid #0f1a2a", zIndex: 20 },
  popupOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.25)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100, pointerEvents: "none" },
  popup: { background: "#0d1520", border: "1px solid #1a2a4a", borderRadius: "20px", padding: "32px 40px", maxWidth: "420px", width: "90%", textAlign: "center", position: "relative", overflow: "hidden", pointerEvents: "auto", boxShadow: "0 8px 40px rgba(0,0,0,0.6)" },
  dragHandle: { padding: "6px 0 10px", cursor: "grab", display: "flex", alignItems: "center", justifyContent: "center", gap: "2px", marginBottom: "4px", userSelect: "none" },
  dragDots: { width: "4px", height: "4px", borderRadius: "50%", background: "#475569" },
  popupGlow: { position: "absolute", top: "-50%", left: "-50%", width: "200%", height: "200%", background: "radial-gradient(circle at center, #f59e0b10 0%, transparent 60%)", pointerEvents: "none" },
  popupIcon: { fontSize: "56px", marginBottom: "8px", position: "relative" },
  popupBadge: { display: "inline-block", padding: "3px 14px", borderRadius: "6px", background: "#f59e0b20", border: "1px solid #f59e0b40", color: "#f59e0b", fontSize: "10px", fontWeight: 800, letterSpacing: "2px", marginBottom: "12px", position: "relative" },
  popupTitle: { fontSize: "24px", fontWeight: 900, color: "#fff", margin: "0 0 8px", position: "relative" },
  popupDesc: { fontSize: "13px", color: "#94a3b8", lineHeight: 1.6, margin: "0 0 20px", position: "relative" },
  popupProgress: { display: "flex", alignItems: "center", gap: "10px", justifyContent: "center", marginBottom: "20px", position: "relative" },
  popupProgressBar: { width: "160px", height: "8px", background: "#1a2a4a", borderRadius: "4px", overflow: "hidden" },
  popupProgressFill: { height: "100%", background: "linear-gradient(90deg, #f59e0b, #facc15)", borderRadius: "4px", transition: "width 0.5s" },
  popupProgressText: { fontSize: "13px", fontWeight: 800, color: "#facc15", fontFamily: "monospace" },
  popupReward: { fontSize: "18px", fontWeight: 800, color: "#4ade80", marginBottom: "16px", position: "relative" },
  popupBtn: { padding: "14px 40px", borderRadius: "12px", background: "linear-gradient(135deg, #f59e0b, #d97706)", color: "#000", border: "none", cursor: "pointer", fontWeight: 800, fontSize: "15px", fontFamily: "inherit", position: "relative", boxShadow: "0 4px 20px rgba(245,158,11,0.3)", transition: "transform 0.15s" },
  taskTracker: { position: "fixed", top: "56px", right: "216px", zIndex: 25, display: "flex", alignItems: "center", gap: "8px", padding: "8px 14px", borderRadius: "10px", background: "#0d1520ee", border: "1px solid #f59e0b40", cursor: "pointer", transition: "transform 0.15s" },
  taskTrackerIcon: { fontSize: "18px" },
  taskTrackerTitle: { fontSize: "11px", fontWeight: 700, color: "#f59e0b" },
  taskTrackerProgress: { fontSize: "10px", color: "#94a3b8", fontFamily: "monospace" },
  bottomLabel: { fontSize: "10px", color: "#94a3b8", fontWeight: 600 },
  coordDisplay: { fontSize: "11px", color: "#f59e0b", fontFamily: "monospace", fontWeight: 700 },
  zoomDisplay: { fontSize: "10px", color: "#64748b" },
};
